services:
  mysql:
    image: mysql:8.0
    container_name: inforsion-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: inforsion_db
      MYSQL_USER: inforsion_user
      MYSQL_PASSWORD: inforsion_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - inforsion-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build: .
    container_name: inforsion-app
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USERNAME: inforsion_user
      DB_PASSWORD: inforsion_password
      SPRING_PROFILES_ACTIVE: docker
      # S3 설정
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET}
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - inforsion-network
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  inforsion-network:
    driver: bridge