spring:
  application:
    name: inforsion-server
  
  datasource:
    url: jdbc:mysql://localhost:3306/inforsion_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: inforsion
    password: inforsion
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: trace